PKGFLAG   = -D_WITH_BDD_DEBUG
EXTHDRS   = util.h rnGen.h myFileUtil.h myWaveform.h myUsage.h bv2.h bv4.h myString.h bst.h bst2.h myCout.h nameMap.h nameMapNode.h nameMapBstNode.h myTruthT.h myGraphAlg.h bddHash.h  bddManager.h  bddNode.h

include ../Makefile.in
include ../Makefile.lib
