PKGFLAG   = 
EXTHDRS   = v3VrfBase.h v3VrfCmd.h v3VrfIPDR.h v3VrfMPDR.h v3VrfKLive.h v3VrfSIM.h v3VrfCITP.h v3VrfFITP.h v3VrfResult.h v3VrfSEC.h v3VrfUMC.h v3VrfBMC.h v3VrfShared.h

include ../Makefile.in
include ../Makefile.lib
