PKGFLAG = -D_WITH_BDD_DEBUG
EXTHDRS = VLGlobe.h vlpBase.h vlpDefine.h vlpEnum.h vlpItoStr.h vlpOpNode.h vlpSubElement.h vlpCtrlNode.h vlpDesign.h vlpHierTree.h vlpModule.h vlpStack.h y.tab.h lib.tab.h parser.h vlpCmd.h vlpCU.h vlpFSM.h
 
LEX  = flex
YACC = bison
YFLAG = -d -v

YYTABC = vlpYacc.tab.c
YYTABH = vlpYacc.tab.h
YYTABC1 = vlpLibYacc.tab.c
YYTABH1 = vlpLibYacc.tab.h

include ../Makefile.in
include ../Makefile.lib

