PKGFLAG = -DBLIF_DEBUG_MODE
EXTHDRS   = cktArithCell.h cktConnect.h cktDefine.h cktIoCell.h cktLogicCell.h cktModule.h cktSeqCell.h cktBLIFile.h cktCell.h cktEnum.h cktLiberty.h cktModelCell.h cktModuleCell.h cktPin.h cktZCell.h

include ../Makefile.in
include ../Makefile.lib
